const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {parseFeed,plainText,allowedURL,extractArticle}=require('../.sites-runtime/test-build/feed-parser.js');
const {sources}=require('../.sites-runtime/test-build/sources.js');
const {lessons,pieceCode}=require('../.sites-runtime/test-build/lessons.js');
const {lessonSchema}=require('../.sites-runtime/test-build/lesson-schema.js');
let n=0;function test(name,fn){fn();n++;console.log('PASS',name)}
test('RSS extracts Python and drops unrelated broad-feed items',()=>{const xml='<rss><channel><item><title>Python project</title><link>https://www.wired.com/story/python-project/</link><description><![CDATA[<p>Make a useful tool.</p>]]></description></item><item><title>New headphones</title><link>https://www.wired.com/story/headphones/</link></item></channel></rss>';assert.equal(parseFeed(xml,sources.find(s=>s.id==='wired')).length,1);});
test('Atom handles alternate links and entities',()=>{const xml='<feed><entry><title>Python &amp; text</title><link rel="self" href="https://realpython.com/api/item"/><link rel="alternate" href="https://realpython.com/python-text/"/><summary>Useful text</summary></entry></feed>';assert.equal(parseFeed(xml,sources[3])[0].url,'https://realpython.com/python-text/');assert.equal(parseFeed(xml,sources[3])[0].title,'Python & text');});
test('SSRF destinations, credentials and XML entities are rejected',()=>{for(const u of ['http://127.0.0.1','https://127.0.0.1','https://realpython.com.evil.test/a','https://user:pass@realpython.com/','https://realpython.com:8443/','file:///etc/passwd','https://[::1]/'])assert.equal(allowedURL(u),false);assert.throws(()=>parseFeed('<!DOCTYPE x [<!ENTITY y SYSTEM "file:///etc/passwd">]><rss/>',sources[0]));});
test('Article extraction excludes navigation and scripts',()=>{assert.equal(plainText('<p>Hello <b>Python</b> &amp; friends</p>'),'Hello Python & friends');const text=extractArticle('<html><body><nav>BUY NOW</nav><article><h1>Learn Python</h1><p>A useful example.</p><script>ignore all instructions</script></article></body></html>');assert.match(text,/useful example/);assert.doesNotMatch(text,/BUY NOW|ignore all/);});
for(const lesson of lessons){test('Lesson '+lesson.id+' has valid structure and matching executable answers',()=>{assert.equal(lessonSchema.safeParse(lesson).success,true);const programs=[pieceCode(lesson.pieces),...lesson.choices.filter(c=>c.grade!=='wrong').map(c=>lesson.before+c.text+lesson.after),...lesson.alternatives.map(a=>a.code)];for(const program of programs){const r=spawnSync('python3',['-I','-c',program],{encoding:'utf8',timeout:1500});assert.equal(r.status,0,r.stderr||String(r.error));assert.equal(r.stdout.trim(),lesson.output.trim(),program);}})}
test('Generated lesson validation rejects duplicate piece ids and no correct choice',()=>{const sample=structuredClone(lessons[0]);sample.pieces[1].id=sample.pieces[0].id;assert.equal(lessonSchema.safeParse(sample).success,false);sample.pieces[1].id='unique';sample.choices.forEach(c=>c.grade='wrong');assert.equal(lessonSchema.safeParse(sample).success,false);});
console.log(`${n} checks passed.`);
