'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Braces, Sparkles, RefreshCw, ArrowUpRight, Bookmark, Check, SlidersHorizontal, ChevronRight, ChevronLeft, Puzzle, Lightbulb, RotateCcw, Plus, Minus, X, LockKeyhole, Code2, Shuffle, CheckCircle2, CircleHelp } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Slider } from '@/components/ui/slider';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { lessons, pieceCode, type Lesson, type Piece } from '@/lib/lessons';
import { sources, starterArticles, type Article } from '@/lib/sources';

type Verdict = {grade:'right'|'okay'|'wrong'; message:string};
type Progress = {saved:string[]; completed:string[]};
const promptChoices=['Explain simply','Why does it work?','Show another way','Give me a hint'];
type FeedResponse={articles:Article[]; updated?:number; health?:Record<string,string>; aiConnected?:boolean; message:string};
type ApiResponses={'/api/feed':FeedResponse;'/api/refresh':FeedResponse;'/api/progress':Progress;'/api/coach':{message:string;grade?:Verdict['grade'];lesson:Lesson}};
async function request<P extends keyof ApiResponses>(path:P,body?:unknown):Promise<ApiResponses[P]>{const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json() as ApiResponses[P]&{error?:string};if(!r.ok)throw Error(d.error||'That did not load. Please try again.');return d;}
function Code({code,label='Open the code'}:{code:string;label?:string}){return <details className="code-detail"><summary><Code2 size={18}/>{label}<Plus size={17}/></summary><pre><code>{code}</code></pre></details>}

export default function Playground(){
 const [tab,setTab]=useState('read'); const [feed,setFeed]=useState<Article[]>(starterArticles);const [feedState,setFeedState]=useState('Starter shelf · refresh to find new reads');const [loading,setLoading]=useState(false);
 const [settings,setSettings]=useState(false);const [sourcePanel,setSourcePanel]=useState(false);const [size,setSize]=useState(18);const [theme,setTheme]=useState('midnight');const [filter,setFilter]=useState('all');const [progress,setProgress]=useState<Progress>({saved:[],completed:[]});const [notice,setNotice]=useState('');const [health,setHealth]=useState<Record<string,string>>({});
 const [index,setIndex]=useState(0);const [generated,setGenerated]=useState<Lesson|null>(null);const lesson=generated||lessons[index];const [mode,setMode]=useState('choose');const [answer,setAnswer]=useState<number|null>(null);const [verdict,setVerdict]=useState<Verdict|null>(null);const [slots,setSlots]=useState<(string|null)[]>([]);const [selected,setSelected]=useState<string|null>(null);const [purpose,setPurpose]=useState<Piece|null>(null);const lastTap=useRef({id:'',time:0});const [remix,setRemix]=useState<string[]>([]);const [coach,setCoach]=useState('');const [thinking,setThinking]=useState(false);const [level,setLevel]=useState(1);const [custom,setCustom]=useState(false);const [customCode,setCustomCode]=useState('');
 const activeCode=mode==='pieces'?slots.map(id=>lesson.pieces.find(p=>p.id===id)).filter(Boolean).map(p=>'    '.repeat(p!.indent)+p!.code).join('\n'):mode==='remix'?(custom?customCode:remix.join('\n')):lesson.before+(answer===null?'…':lesson.choices[answer].text)+lesson.after;
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('python-display')||'{}');if(p.size)setSize(p.size);if(p.theme)setTheme(p.theme);}catch{} request('/api/feed').then(d=>{if(d.articles.length){setFeed(d.articles);setFeedState(d.updated?'Updated '+new Date(d.updated).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Your Python reading list');}if(d.health)setHealth(d.health);if(d.aiConnected&&(!d.updated||Date.now()-d.updated>3600000))void refresh();}).catch(()=>setFeedState('Starter shelf · live feed not connected'));
 request('/api/progress').then(setProgress).catch(()=>{});
 },[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--reading-size',size+'px');localStorage.setItem('python-display',JSON.stringify({size,theme}));},[size,theme]);
 useEffect(()=>{setAnswer(null);setVerdict(null);setSlots(lesson.pieces.map(()=>null));setSelected(null);setRemix([]);setCoach('');setCustom(false);setCustomCode('');},[lesson]);
 useEffect(()=>{const mc=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!mc)return;const ac=new AbortController();Promise.resolve(mc.registerTool({name:'open_python_playground_view',description:'Navigate to the reading feed or learning playground.',inputSchema:{type:'object',properties:{view:{enum:['read','play']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{view:string})=>{if(!['read','play'].includes(input.view))throw Error('Choose read or play.');setTab(input.view);return{view:input.view};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[]);
 async function refresh(){if(loading)return;setLoading(true);setNotice('');try{const d=await request('/api/refresh',{});if(d.articles.length)setFeed(d.articles);setFeedState(d.message);setHealth(d.health||{});}catch(e){setNotice((e as Error).message);}finally{setLoading(false)}}
 async function save(id:string){try{const d=await request('/api/progress',{action:'bookmark',id,saved:!progress.saved.includes(id)});setProgress(d);}catch{setNotice('Could not save this read. Your private storage is not connected yet.');}}
 async function complete(){try{setProgress(await request('/api/progress',{action:'complete',id:lesson.id}));}catch{setNotice('Nice work. Progress could not be saved yet.');}}
 function choose(i:number){setAnswer(i);const c=lesson.choices[i];setVerdict({grade:c.grade,message:c.why});if(c.grade!=='wrong')void complete();}
 function tapPiece(p:Piece){const now=Date.now();if(lastTap.current.id===p.id&&now-lastTap.current.time<350){setPurpose(p);}else setSelected(p.id);lastTap.current={id:p.id,time:now};}
 function place(i:number){if(!selected){if(slots[i])setSelected(slots[i]);return;}const n=[...slots];const old=n.indexOf(selected);if(old>=0)n[old]=n[i];n[i]=selected;setSlots(n);setSelected(null);setVerdict(null);}
 function checkPuzzle(){const correct=slots.every((id,i)=>id===lesson.pieces[i].id);setVerdict({grade:correct?'right':'wrong',message:correct?'It fits. '+lesson.explanation:'Nearly there. Start with the setup, then the check, then the action. Double-tap a piece for a clue.'});if(correct)void complete();}
 async function ask(question:string){if(thinking)return;setThinking(true);setCoach('');try{const d=await request('/api/coach',{action:question==='Review my approach'?'review':'explain',lesson,code:activeCode,question});setCoach(d.message);if(d.grade){setVerdict({grade:d.grade,message:d.message});if(d.grade!=='wrong')void complete();}}catch(e){setCoach((e as Error).message);}finally{setThinking(false)}}
 async function newChallenge(){if(thinking)return;setThinking(true);try{const d=await request('/api/coach',{action:'generate',level,previous:lesson.concept});setGenerated(d.lesson);setMode('choose');}catch(e){setCoach((e as Error).message);}finally{setThinking(false)}}
 function next(){setGenerated(null);setIndex((index+1)%lessons.length);setMode('choose');}
 const shown=feed.filter(a=>filter==='saved'?progress.saved.includes(a.id):filter==='quick'?(a.minutes??99)<=5:true);
 const palette=[...new Set([...lesson.pieces.map(p=>'    '.repeat(p.indent)+p.code),...lesson.alternatives.flatMap(a=>a.code.split('\n')),'else:','finally:','    pass'])];
 return <div className="app-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="Python Playground home"><span className="brand-mark"><Braces size={25}/></span><span>python<span className="brand-soft"> playground</span></span></a><div className="top-actions"><span className="private-label"><LockKeyhole size={14}/> Just for you</span><button className="icon-button" onClick={()=>setSettings(true)} aria-label="Reading settings"><SlidersHorizontal size={21}/></button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="main-tabs"><div className="navigation"><TabsList className="main-tab-list"><TabsTrigger value="read"><BookOpen size={19}/> Reading room</TabsTrigger><TabsTrigger value="play"><Puzzle size={19}/> Playground</TabsTrigger></TabsList><span className="nav-note">A little curiosity goes a long way.</span></div>
 {notice&&<div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={18}/></button></div>}
 <TabsContent value="read"><div className="workspace-head"><div><span className="eyebrow">YOUR PYTHON CORNER</span><h1>A few good reads.</h1><p className="muted">Useful ideas. The short version first.</p></div><button className="button secondary refresh" onClick={refresh} disabled={loading}><RefreshCw size={18} className={loading?'spinning':''}/>{loading?'Finding good reads…':'Find fresh reads'}</button></div>
 <div className="reading-layout"><section aria-label="Python articles"><div className="feed-tools"><div className="chip-row">{[['all','For you'],['quick','Quick reads'],['saved','Saved']].map(([v,label])=><button key={v} aria-pressed={filter===v} className={'chip '+(filter===v?'active':'')} onClick={()=>setFilter(v)}>{label}</button>)}</div><span className="feed-status">{feedState}</span></div>
 {shown.length===0?<div className="empty"><Bookmark/><h2>{filter==='saved'?'Keep something for later.':'No reads here yet.'}</h2><p>{filter==='saved'?'Tap the bookmark beside an article.':'Try the full feed, or find fresh reads.'}</p></div>:shown.map((a,i)=><article className={'article-card '+(i===0?'featured':'')} key={a.id}><div className="article-meta"><span className={'source-icon '+a.category}>{a.source.slice(0,2).toUpperCase()}</span><span>{a.source}</span><span className="dot-separator">·</span><span>{a.minutes?`${a.minutes} min ${a.basis==='starter'?'suggested':'read'}`:'Reading time unavailable'}</span><button className={'icon-button bookmark '+(progress.saved.includes(a.id)?'is-saved':'')} aria-label={progress.saved.includes(a.id)?'Unsave '+a.title:'Save '+a.title} aria-pressed={progress.saved.includes(a.id)} onClick={()=>save(a.id)}><Bookmark size={20} fill={progress.saved.includes(a.id)?'currentColor':'none'}/></button></div><div className="article-tags"><span className="tag">{a.category}</span>{a.basis==='starter'&&<span className="tiny-label">Starter guide</span>}{a.basis==='excerpt'&&<span className="tiny-label">From feed excerpt</span>}{a.basis==='headline'&&<span className="tiny-label">Headline only · not summarized</span>}{a.ai&&<span className="tiny-label"><Sparkles size={12}/> AI picked</span>}</div><h2>{a.title}</h2><p className="takeaway">{a.takeaway}</p><details className="article-details"><summary>Key points <Plus size={16}/></summary><ul>{a.points.map((p,j)=><li key={j}>{p}</li>)}</ul>{a.basis==='full'&&<p className="tiny-label">AI summary of extracted article text · reading time estimated at 220 words/minute.</p>}{a.basis==='excerpt'&&<p className="tiny-label">The full article was unavailable. This summary covers only its feed excerpt; reading time is an excerpt estimate.</p>}</details>{a.code&&<Code code={a.code} label="Try the idea in code"/>}<div className="article-footer"><span className="article-reason">{a.reason}</span><a href={a.url} target="_blank" rel="noopener noreferrer" className="text-link">Read {a.basis==='starter'?'guide':'article'} <ArrowUpRight size={17}/></a></div></article>)}
 </section><aside className="reading-aside"><div className="mini-play"><span className="eyebrow"><Sparkles size={16}/> PUT IT INTO PLAY</span><h2>One tiny puzzle.<br/>One useful idea.</h2><div className="mini-code"><span>if</span> curious:<br/>&nbsp;&nbsp;&nbsp;&nbsp;play<span>()</span></div><p>Pick an answer. Move a piece.<br/>See what happens.</p><button className="button primary" onClick={()=>setTab('play')}>Let’s play <ChevronRight size={18}/></button></div><div className="source-note"><h3>Your reading mix</h3><div className="source-stack">{['Python.org','Python Cheatsheet','Real Python','How-To Geek','WIRED','Tom’s Hardware'].map((s,i)=><span key={s}><span className={'source-pip pip-'+i}/>{s}</span>)}</div><p>Python programming only. Practical, interesting, worth your time.</p><button className="text-link" onClick={()=>setSourcePanel(true)}>View sources <ChevronRight size={16}/></button></div></aside></div></TabsContent>
 <TabsContent value="play"><div className="workspace-head"><div><span className="eyebrow">SMALL WINS, REAL PYTHON</span><h1>Follow your curiosity.</h1><p className="muted">No timer. No lost lives. Try another way.</p></div><div className="progress-pill"><CheckCircle2 size={18}/>{progress.completed.length} ideas explored</div></div><div className="play-layout"><section className="exercise"><div className="exercise-top"><span className="tag">{lesson.concept}</span><span className="tiny-label">Level {lesson.level} · {generated?'AI suggested challenge':`${index+1} of ${lessons.length}`}</span></div><h2>{lesson.title}</h2><p className="task">{lesson.task}</p><Tabs value={mode} onValueChange={v=>{setMode(v);setVerdict(null);setCoach('')}}><TabsList className="exercise-tabs"><TabsTrigger value="choose">Fill a gap</TabsTrigger><TabsTrigger value="pieces">Piece it together</TabsTrigger><TabsTrigger value="remix">My own way</TabsTrigger></TabsList>
 <TabsContent value="choose"><div className="code-stage"><span className="code-caption">PYTHON</span><pre><code>{lesson.before}<span className={'blank '+(verdict?.grade||'')}>{answer===null?'  choose below  ':lesson.choices[answer].text}</span>{lesson.after}</code></pre></div><div className="choices">{lesson.choices.map((c,i)=><button key={i} onClick={()=>choose(i)} className={'answer-button '+(answer===i?c.grade:'')} aria-pressed={answer===i}><span className="choice-letter">{String.fromCharCode(65+i)}</span><code>{c.text}</code>{answer===i&&(c.grade==='right'?<Check size={21}/>:c.grade==='okay'?<Lightbulb size={21}/>:<RotateCcw size={20}/>)}</button>)}</div></TabsContent>
 <TabsContent value="pieces"><p className="touch-hint">Tap a piece, then a space. Double-tap any piece for its meaning.</p><div className="puzzle-board">{slots.map((id,i)=>{const p=lesson.pieces.find(p=>p.id===id);return <button key={i} className={'puzzle-slot '+(p?'filled color-'+lesson.pieces.indexOf(p):'')+(selected===id&&id?' selected':'')} onClick={()=>place(i)} onDoubleClick={()=>p&&setPurpose(p)} aria-label={`Space ${i+1}${p?': '+p.code:''}`}><span className="slot-number">{i+1}</span>{p?<code style={{paddingInlineStart:`${p.indent*.7}rem`}}>{p.code}</code>:<span>{selected?'Place here':'Tap to place a piece'}</span>}</button>})}</div><div className="piece-tray">{[...lesson.pieces].reverse().map((p)=><button key={p.id} onClick={()=>tapPiece(p)} aria-pressed={selected===p.id} className={'piece color-'+lesson.pieces.indexOf(p)+(selected===p.id?' selected':'')+(slots.includes(p.id)?' placed':'')}><span>{slots.includes(p.id)?<Check size={16}/>:<Puzzle size={16}/>}</span><code>{p.code}</code></button>)}</div><div className="row-actions"><button className="button primary" disabled={slots.some(s=>!s)} onClick={checkPuzzle}><Check size={18}/>Check the pieces</button><button className="icon-button" aria-label="Reset pieces" onClick={()=>{setSlots(lesson.pieces.map(()=>null));setSelected(null);setVerdict(null)}}><RotateCcw size={19}/></button>{selected&&<button className="icon-button" aria-label="Explain selected piece" onClick={()=>setPurpose(lesson.pieces.find(p=>p.id===selected)||null)}><CircleHelp size={20}/></button>}</div></TabsContent>
 <TabsContent value="remix"><p className="touch-hint">Start with an approach, then rearrange or add pieces. Different can be good.</p><div className="chip-row remix-presets">{lesson.alternatives.map(a=><button className="chip" key={a.name} onClick={()=>{setRemix(a.code.split('\n'));setCoach(a.why);setCustom(false);setVerdict(null)}}>{a.name}</button>)}</div>{custom?<textarea aria-label="Optional Python code editor" value={customCode} spellCheck={false} onChange={e=>setCustomCode(e.target.value)} className="custom-editor"/>:<div className="remix-board">{remix.length===0?<p>Choose an approach above, or tap pieces below.</p>:remix.map((line,i)=><div className={'remix-line color-'+i%5} key={i}><code>{line}</code><div className="line-tools"><button aria-label={`Move line ${i+1} up`} disabled={i===0} onClick={()=>setRemix(r=>{const a=[...r];[a[i-1],a[i]]=[a[i],a[i-1]];return a})}>↑</button><button aria-label={`Indent line ${i+1}`} onClick={()=>setRemix(r=>r.map((x,j)=>j===i?'    '+x:x))}>→</button><button aria-label={`Outdent line ${i+1}`} onClick={()=>setRemix(r=>r.map((x,j)=>j===i?x.replace(/^ {1,4}/,''):x))}>←</button><button aria-label={`Remove line ${i+1}`} onClick={()=>setRemix(r=>r.filter((_,j)=>j!==i))}><X size={17}/></button></div></div>)}</div>}<details className="toolbox"><summary><Plus size={17}/>Add a code piece</summary><div className="toolbox-pieces">{palette.map((p,i)=><button key={i} className={'piece color-'+i%5} onClick={()=>{setRemix(r=>[...r,p]);setCustom(false)}}><code>{p}</code><Plus size={16}/></button>)}</div></details><div className="row-actions"><button className="button primary" disabled={thinking||(!custom&&!remix.length)|| (custom&&!customCode.trim())} onClick={()=>ask('Review my approach')}><Sparkles size={18}/>Review my approach</button><button className="text-link" onClick={()=>{setCustomCode(remix.join('\n'));setCustom(!custom)}}>{custom?'Back to touch':'Optional typing'}</button></div><p className="tiny-label">AI review checks the idea. It does not run your code.</p></TabsContent></Tabs>
 {verdict&&<div role="status" className={'feedback '+verdict.grade}><span>{verdict.grade==='right'?<CheckCircle2/>:verdict.grade==='okay'?<Lightbulb/>:<RotateCcw/>}</span><div><strong>{verdict.grade==='right'?'That works.':verdict.grade==='okay'?'Works, with a trade-off.':'A useful experiment.'}</strong><p>{verdict.message}</p></div></div>}{verdict&&verdict.grade!=='wrong'&&mode!=='remix'&&<Code code={lesson.output} label="See the expected output"/>}
 <div className="exercise-footer"><button className="text-link" onClick={()=>{setGenerated(null);setIndex((index+lessons.length-1)%lessons.length)}}><ChevronLeft size={17}/>Previous</button><button className="button secondary" onClick={next}>Another idea <ChevronRight size={18}/></button></div></section><aside className="coach-card"><span className="eyebrow"><Sparkles size={17}/> A LITTLE HELP</span><h2>Let’s make it click.</h2><p>Ask in one tap.</p><div className="coach-prompts">{promptChoices.map(p=><button key={p} disabled={thinking} onClick={()=>ask(p)}>{p}<ChevronRight size={16}/></button>)}</div><div aria-live="polite" className="coach-reply">{thinking?<p className="muted">Thinking it through…</p>:coach?<p>{coach}</p>:<p className="muted">{lesson.explanation}</p>}</div><div className="fresh-challenge"><h3>Change the pace</h3><div className="chip-row">{[1,2,3].map(n=><button className={'chip '+(level===n?'active':'')} key={n} aria-pressed={level===n} onClick={()=>setLevel(n)}>{['Gentle','Stretch','Challenge'][n-1]}</button>)}</div><button className="button secondary" onClick={newChallenge} disabled={thinking}><Shuffle size={18}/>Make a fresh puzzle</button></div></aside></div></TabsContent></Tabs>
 <footer className="footer"><span><Braces size={16}/> Small ideas. More possibilities.</span><button onClick={()=>setSourcePanel(true)} className="text-link">Sources & connections</button></footer>
 <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="settings-sheet"><SheetHeader><SheetTitle>Make yourself comfortable.</SheetTitle><SheetDescription>These display choices stay on this device.</SheetDescription></SheetHeader><div className="sheet-body"><h3>Text size <span className="muted">{size}px</span></h3><div className="font-control"><button className="icon-button" aria-label="Smaller text" onClick={()=>setSize(Math.max(16,size-1))}><Minus/></button><Slider aria-label="Text size" value={[size]} min={16} max={28} step={1} onValueChange={v=>setSize(v[0])}/><button className="icon-button" aria-label="Larger text" onClick={()=>setSize(Math.min(28,size+1))}><Plus/></button></div><h3>Appearance</h3><RadioGroup value={theme} onValueChange={setTheme} className="theme-options" aria-label="Appearance">{[['midnight','Midnight'],['system','Match device'],['light','Daylight']].map(([v,l])=><label key={v} className={'button secondary '+(theme===v?'chosen':'')}>{l}<RadioGroupItem value={v} aria-label={l}/></label>)}</RadioGroup><p className="sample">A little breathing room.<br/>A clearer way to learn.</p><p className="muted">Lines wrap. Pinch to zoom works. Motion follows your device preference.</p></div></SheetContent></Sheet>
 <Sheet open={sourcePanel} onOpenChange={setSourcePanel}><SheetContent className="settings-sheet"><SheetHeader><SheetTitle>Your Python sources</SheetTitle><SheetDescription>Broad feeds are filtered for Python programming. Refresh checks for new articles.</SheetDescription></SheetHeader><div className="sheet-body source-list">{sources.map(s=><div key={s.id}><a className="text-link" href={s.home} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={15}/></a><p className="tiny-label">{health[s.id]||'Not checked yet'}</p></div>)}<p className="muted">Summaries say whether the full text or only an excerpt was available. Blocked and paid articles are never presented as fully read.</p><p className="muted">AI needs a server-side OpenAI connection. Reading and practice history stay in the private site database.</p></div></SheetContent></Sheet>
 <Sheet open={!!purpose} onOpenChange={v=>!v&&setPurpose(null)}><SheetContent side="bottom" className="purpose-sheet"><SheetHeader><SheetTitle>What this piece does</SheetTitle><SheetDescription>{purpose?.purpose}</SheetDescription></SheetHeader><pre><code>{purpose?.code}</code></pre></SheetContent></Sheet>
 </div>
}
