export type Choice = { text: string; grade: 'right' | 'okay' | 'wrong'; why: string };
export type Piece = { id: string; code: string; purpose: string; indent: number };
export type Lesson = { id: string; title: string; concept: string; task: string; level: number; before: string; after: string; choices: Choice[]; pieces: Piece[]; output: string; explanation: string; alternatives: { name: string; code: string; why: string }[] };
export const lessons: Lesson[] = [
  { id: 'filter-even', title: 'Keep the good stuff', concept: 'Make a choice', level: 1, task: 'Keep only the even numbers from 1 to 6.', before: 'for n in range(1, 7):\n    if ', after: ':\n        print(n)', choices: [
    {text:'n % 2 == 0',grade:'right',why:'Yes. Dividing by 2 leaves nothing over: an even number.'},
    {text:'n in [2, 4, 6]',grade:'okay',why:'Works for this list. The remainder check also works when the range changes.'},
    {text:'n % 2 == 1',grade:'wrong',why:'That keeps odd numbers. Try checking for no remainder.'}
  ], pieces:[{id:'a',code:'for n in range(1, 7):',purpose:'Visit the numbers 1 through 6.',indent:0},{id:'b',code:'if n % 2 == 0:',purpose:'Keep a number when it divides evenly by 2.',indent:1},{id:'c',code:'print(n)',purpose:'Show the number that passed the check.',indent:2}], output:'2\n4\n6', explanation:'The loop visits each number. The if line lets only even numbers reach print.', alternatives:[
    {name:'Step by two',code:'for n in range(2, 7, 2):\n    print(n)',why:'Skip the odd numbers entirely. A small, direct solution.'},
    {name:'While loop',code:'n = 2\nwhile n <= 6:\n    print(n)\n    n += 2',why:'Keep going until the number passes 6.'},
    {name:'Generator',code:'evens = (n for n in range(1, 7) if n % 2 == 0)\nfor n in evens:\n    print(n)',why:'Prepare a stream of matching numbers, then read it.'},
    {name:'Walrus',code:'n = 0\nwhile (n := n + 2) <= 6:\n    print(n)',why:'Update the number inside the check. Valid, though less familiar to many readers.'}
  ]},
  { id:'clean-names',title:'A little spring cleaning',concept:'Tidy text',level:1,task:'Remove spaces at the edges of a name.',before:'name = "  Ada  "\nclean = ',after:'\nprint(clean)',choices:[{text:'name.strip()',grade:'right',why:'Exactly. strip removes extra space at either edge.'},{text:'name.replace(" ", "")',grade:'okay',why:'Works here, but also removes spaces inside names like Ada Lovelace.'},{text:'name.upper()',grade:'wrong',why:'That changes letters to capitals. It leaves the spaces.'}],pieces:[{id:'a',code:'name = "  Ada  "',purpose:'Start with a name surrounded by spaces.',indent:0},{id:'b',code:'clean = name.strip()',purpose:'Make a tidied copy of the name.',indent:0},{id:'c',code:'print(clean)',purpose:'Show the tidied name.',indent:0}],output:'Ada',explanation:'Strings are text. strip makes a new string without the spaces at the edges.',alternatives:[{name:'One line',code:'print("  Ada  ".strip())',why:'No extra name needed when you only use the result once.'}]},
  {id:'skip-empty',title:'Leave the blanks behind',concept:'Useful shortcuts',level:2,task:'Print only the nonempty items.',before:'items = ["read", "", "play"]\nfor item in items:\n    if ',after:':\n        print(item)',choices:[{text:'item',grade:'right',why:'Empty text counts as false. Nonempty text counts as true.'},{text:'len(item) > 0',grade:'okay',why:'Correct. Checking item directly says the same thing with less code.'},{text:'item is not None',grade:'wrong',why:'An empty string is still not None, so the blank slips through.'}],pieces:[{id:'a',code:'items = ["read", "", "play"]',purpose:'Make a list with one blank item.',indent:0},{id:'b',code:'for item in items:',purpose:'Look at each item in turn.',indent:0},{id:'c',code:'if item:',purpose:'Continue only if the text is nonempty.',indent:1},{id:'d',code:'print(item)',purpose:'Show the useful item.',indent:2}],output:'read\nplay',explanation:'An empty string is false in a condition. This makes it easy to skip blanks.',alternatives:[{name:'Skip early',code:'for item in ["read", "", "play"]:\n    if not item:\n        continue\n    print(item)',why:'continue skips to the next item. Useful when more work follows.'},{name:'Generator',code:'items = ["read", "", "play"]\nfor item in (x for x in items if x):\n    print(item)',why:'Filter the stream before printing.'}]},
  {id:'countdown',title:'Three, two, one',concept:'Keep going',level:2,task:'Count down from 3 and stop before zero.',before:'n = 3\nwhile n > 0:\n    print(n)\n    ',after:'',choices:[{text:'n -= 1',grade:'right',why:'One step closer to zero each time.'},{text:'n = n - 1',grade:'okay',why:'Correct. The shorter form is a common way to say it.'},{text:'n += 1',grade:'wrong',why:'That moves away from zero. The loop would never finish.'}],pieces:[{id:'a',code:'n = 3',purpose:'Choose where to start.',indent:0},{id:'b',code:'while n > 0:',purpose:'Repeat only while the number is positive.',indent:0},{id:'c',code:'print(n)',purpose:'Show the current number before changing it.',indent:1},{id:'d',code:'n -= 1',purpose:'Reduce the number so the loop can end.',indent:1}],output:'3\n2\n1',explanation:'A while loop needs a way to stop. Subtracting one makes the condition false eventually.',alternatives:[{name:'A range',code:'for n in range(3, 0, -1):\n    print(n)',why:'A negative step counts backward without a separate update.'}]},
  {id:'safe-value',title:'A friendly fallback',concept:'Handle a surprise',level:3,task:'Show a helpful message when text cannot become a number.',before:'try:\n    number = int("hello")\n',after:':\n    print("Try a number")',choices:[{text:'except ValueError',grade:'right',why:'Catch the specific problem: text that cannot become a number.'},{text:'except Exception',grade:'okay',why:'It catches this too, but can hide unrelated bugs.'},{text:'finally',grade:'wrong',why:'finally always runs, but does not catch the error. The error would still escape.'}],pieces:[{id:'a',code:'try:',purpose:'Try the operation that might fail.',indent:0},{id:'b',code:'number = int("hello")',purpose:'Attempt to turn the text into a number.',indent:1},{id:'c',code:'except ValueError:',purpose:'Handle text that cannot be converted.',indent:0},{id:'d',code:'print("Try a number")',purpose:'Explain the problem in a useful way.',indent:1}],output:'Try a number',explanation:'except handles a failure. finally is for cleanup that should happen whether or not an error occurs.',alternatives:[{name:'Check first',code:'text = "hello"\nif text.isdecimal():\n    number = int(text)\nelse:\n    print("Try a number")',why:'This works for the example, but rejects valid signed numbers like -3.'}]},
  {id:'first-match',title:'Find it and stop',concept:'Make less work',level:3,task:'Find the first number above 10, or use None.',before:'numbers = [4, 8, 12, 20]\nfirst = ',after:'\nprint(first)',choices:[{text:'next((n for n in numbers if n > 10), None)',grade:'right',why:'Find the first match without building a whole extra list.'},{text:'[n for n in numbers if n > 10][0]',grade:'wrong',why:'Works for this list, but raises an error if no numbers match.'},{text:'next((n for n in numbers if n >= 10), None)',grade:'wrong',why:'That also accepts 10. The goal says above 10.'}],pieces:[{id:'a',code:'numbers = [4, 8, 12, 20]',purpose:'Start with some numbers.',indent:0},{id:'b',code:'matches = (n for n in numbers if n > 10)',purpose:'Prepare matching numbers one at a time.',indent:0},{id:'c',code:'first = next(matches, None)',purpose:'Take one match; fall back to None if there is no match.',indent:0},{id:'d',code:'print(first)',purpose:'Show the first match.',indent:0}],output:'12',explanation:'A generator produces items on demand. next asks for just one.',alternatives:[{name:'Loop and break',code:'first = None\nfor n in [4, 8, 12, 20]:\n    if n > 10:\n        first = n\n        break\nprint(first)',why:'More lines, but very explicit. Readability is a valid reason to choose it.'}]}
];
export const pieceCode = (pieces: Piece[]) => pieces.map(p=>'    '.repeat(p.indent)+p.code).join('\n');
